/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          'mughal-green': 'var(--brand-mughal-green)',
          'mughal-green-2': 'var(--brand-mughal-green-2)',
          'pistachio': 'var(--brand-pistachio)',
          'pistachio-2': 'var(--brand-pistachio-2)',
          'bone': 'var(--brand-bone)',
          'paper': 'var(--brand-paper)',
        },
        surface: {
          primary: 'var(--surface-primary)',
          paper: 'var(--surface-paper)',
          bone: 'var(--surface-bone)',
          'green-panel': 'var(--surface-green-panel)',
          'pistachio-panel': 'var(--surface-pistachio-panel)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverse: 'var(--text-inverse)',
          'inverse-muted': 'var(--text-inverse-muted)',
          'on-green': 'var(--text-on-green)',
          'on-bone': 'var(--text-on-bone)',
          link: 'var(--text-link)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
          'inverse-subtle': 'var(--border-inverse-subtle)',
        },
        state: {
          success: 'var(--state-success)',
          'success-soft': 'var(--state-success-soft)',
          warning: 'var(--state-warning)',
          'warning-soft': 'var(--state-warning-soft)',
          danger: 'var(--state-danger)',
          'danger-soft': 'var(--state-danger-soft)',
          info: 'var(--state-info)',
          'info-soft': 'var(--state-info-soft)',
        },
        focus: {
          ring: 'var(--focus-ring)',
          'ring-strong': 'var(--focus-ring-strong)',
        },
      },
      fontFamily: {
        sans: [
          'Sora',
          'Inter',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '16px', letterSpacing: '0' }],
        'sm': ['14px', { lineHeight: '20px', letterSpacing: '0' }],
        'md': ['16px', { lineHeight: '24px', letterSpacing: '0' }],
        'lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.1px' }],
        'xl': ['22px', { lineHeight: '30px', letterSpacing: '-0.2px' }],
        '2xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.3px' }],
        '3xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.5px' }],
        '4xl': ['56px', { lineHeight: '62px', letterSpacing: '-0.8px' }],
        '5xl': ['72px', { lineHeight: '78px', letterSpacing: '-1.0px' }],
      },
      spacing: {
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '40px',
        '10': '48px',
        '11': '56px',
        '12': '64px',
        '13': '80px',
        '14': '96px',
        '15': '120px',
      },
      borderRadius: {
        // Project rule: all corners are 4px (no mixed radii, no pills)
        'xs': '4px',
        'sm': '4px',
        'md': '4px',
        'lg': '4px',
        'xl': '4px',
        '2xl': '4px',
        'pill': '4px',
      },
      boxShadow: {
        'sm': '0 1px 1px rgba(11, 15, 12, 0.06), 0 8px 18px rgba(11, 15, 12, 0.08)',
        'md': '0 2px 10px rgba(11, 15, 12, 0.10), 0 18px 40px rgba(11, 15, 12, 0.12)',
        'lg': '0 8px 22px rgba(11, 15, 12, 0.12), 0 28px 70px rgba(11, 15, 12, 0.16)',
      },
      transitionDuration: {
        'fast': '120ms',
        'normal': '180ms',
        'slow': '260ms',
      },
      transitionTimingFunction: {
        'standard': 'cubic-bezier(0.2, 0.0, 0.0, 1.0)',
        'decelerate': 'cubic-bezier(0.0, 0.0, 0.0, 1.0)',
        'accelerate': 'cubic-bezier(0.4, 0.0, 1.0, 1.0)',
      },
    },
  },
  plugins: [],
}

