import type { CompanySearchResult } from '@/app/[locale]/app/search/actions'
import type { PlanId } from '@/lib/stripe/config'

export interface PDFOptions {
  planId?: PlanId
  locale?: 'ro' | 'en'
  includeWatermark?: boolean
  companyLogo?: string
  customBranding?: {
    color: string
    name: string
  }
}

/**
 * Generate a PDF report for a company using browser print
 * This creates a print-friendly HTML view that can be saved as PDF
 * Enhanced with plan-based features and watermarking
 */
export function generateCompanyPDF(
  company: CompanySearchResult,
  options: PDFOptions = {}
): void {
  const {
    planId = 'free',
    locale = 'ro',
    includeWatermark = planId === 'free',
    companyLogo,
    customBranding,
  } = options
  // Create a new window for the print view
  const printWindow = window.open('', '_blank')

  if (!printWindow) {
    alert('Vă rugăm să permiteți pop-up-urile pentru a genera PDF-ul')
    return
  }

  // Get risk color based on level
  const getRiskColor = (level: string) => {
    switch (level) {
      case 'GREEN':
        return { bg: '#22C55E', text: '#22C55E', light: '#22C55E20' }
      case 'YELLOW':
        return { bg: '#F59E0B', text: '#F59E0B', light: '#F59E0B20' }
      case 'RED':
        return { bg: '#EF4444', text: '#EF4444', light: '#EF444420' }
      default:
        return { bg: '#9CA3AF', text: '#6B7280', light: '#F3F4F6' }
    }
  }

  const riskColors = company.riskScore ? getRiskColor(company.riskScore.level) : getRiskColor('UNKNOWN')

  const currentDate = new Date().toLocaleDateString(locale === 'ro' ? 'ro-RO' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })

  // Localized text
  const text = {
    ro: {
      title: 'Raport Risc Companie',
      brand: 'MarketRisk.ro',
      generatedAt: 'Generat la',
      riskScore: 'Scor de Risc',
      companyInfo: 'Informații Companie',
      riskFactors: 'Factori de Risc',
      address: 'Adresă',
      companyStatus: 'Status Companie',
      vatStatus: 'Status TVA',
      active: 'Activ',
      inactive: 'Inactiv',
      unavailable: 'Nedisponibil',
      vatSplitRegime: 'Regim TVA la încasare',
      stateDebts: 'Datorii la stat',
      noDebts: 'Fără datorii',
      activeLawsuits: 'Procese active',
      lostCases2y: 'Procese pierdute (2 ani)',
      insolvencyStatus: 'Status Insolvență',
      noProblem: 'Fără probleme',
      bankruptcyFiling: 'Cerere faliment',
      yes: 'Da',
      no: 'Nu',
      points: 'puncte',
      footer1: 'Raport generat de MarketRisk.ro - Toate drepturile rezervate',
      footer2: 'Acest raport este generat automat pe baza datelor disponibile la momentul generării.',
      printButton: 'Salvează ca PDF / Printează',
      closeButton: 'Închide',
      watermark: 'RAPORT GRATUIT',
      watermarkNote: 'Acest raport este generat cu planul gratuit MarketRisk. Pentru rapoarte fără marcaj de apă și funcții avansate, actualizați la un plan premium.',
    },
    en: {
      title: 'Company Risk Report',
      brand: 'MarketRisk.ro',
      generatedAt: 'Generated at',
      riskScore: 'Risk Score',
      companyInfo: 'Company Information',
      riskFactors: 'Risk Factors',
      address: 'Address',
      companyStatus: 'Company Status',
      vatStatus: 'VAT Status',
      active: 'Active',
      inactive: 'Inactive',
      unavailable: 'Unavailable',
      vatSplitRegime: 'VAT cash accounting',
      stateDebts: 'State debts',
      noDebts: 'No debts',
      activeLawsuits: 'Active lawsuits',
      lostCases2y: 'Lost cases (2 years)',
      insolvencyStatus: 'Insolvency Status',
      noProblem: 'No problems',
      bankruptcyFiling: 'Bankruptcy filing',
      yes: 'Yes',
      no: 'No',
      points: 'points',
      footer1: 'Report generated by MarketRisk.ro - All rights reserved',
      footer2: 'This report is automatically generated based on data available at the time of generation.',
      printButton: 'Save as PDF / Print',
      closeButton: 'Close',
      watermark: 'FREE REPORT',
      watermarkNote: 'This report was generated with MarketRisk free plan. For reports without watermark and advanced features, upgrade to a premium plan.',
    },
  }

  const t = text[locale]
  const brandColor = customBranding?.color || '#005A41'
  const brandName = customBranding?.name || t.brand

  // Build the HTML content
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="ro">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Raport Risc - ${company.companyName}</title>
      <style>
        @media print {
          @page {
            margin: 1.5cm;
            size: A4;
          }
          body {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          .no-print {
            display: none;
          }
          .page-break {
            page-break-before: always;
          }
        }

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica', 'Arial', sans-serif;
          color: #111827;
          line-height: 1.6;
          max-width: 210mm;
          margin: 0 auto;
          padding: 20px;
          background: white;
        }

        .header {
          background: #005A41;
          color: white;
          padding: 30px 40px;
          margin: -20px -20px 30px -20px;
          text-align: center;
        }

        .header h1 {
          font-size: 28px;
          margin-bottom: 8px;
          font-weight: 700;
        }

        .header .brand {
          font-size: 14px;
          opacity: 0.9;
          margin-bottom: 8px;
        }

        .header .date {
          font-size: 11px;
          opacity: 0.8;
        }

        .company-header {
          margin-bottom: 25px;
        }

        .company-name {
          font-size: 24px;
          font-weight: 700;
          color: #111827;
          margin-bottom: 8px;
        }

        .company-meta {
          font-size: 12px;
          color: #6B7280;
        }

        .risk-box {
          border: 2px solid ${riskColors.bg};
          border-radius: 8px;
          padding: 20px;
          margin-bottom: 25px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .risk-label {
          font-size: 14px;
          font-weight: 600;
          color: #111827;
        }

        .risk-score {
          text-align: right;
        }

        .risk-value {
          font-size: 32px;
          font-weight: 700;
          color: ${riskColors.text};
        }

        .risk-level {
          font-size: 12px;
          color: ${riskColors.text};
          font-weight: 600;
        }

        .risk-explanation {
          background: #F9FAFB;
          padding: 15px;
          border-radius: 6px;
          margin-bottom: 25px;
          font-size: 11px;
          color: #6B7280;
          font-style: italic;
        }

        .section {
          margin-bottom: 25px;
        }

        .section-title {
          font-size: 16px;
          font-weight: 700;
          color: #111827;
          margin-bottom: 15px;
          padding-bottom: 8px;
          border-bottom: 2px solid #E5E7EB;
        }

        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
          font-size: 11px;
        }

        th, td {
          padding: 10px;
          text-align: left;
          border-bottom: 1px solid #E5E7EB;
        }

        th {
          background: #F9FAFB;
          font-weight: 600;
          color: #111827;
        }

        tr:last-child td {
          border-bottom: none;
        }

        .info-row {
          display: grid;
          grid-template-columns: 180px 1fr;
          padding: 8px 0;
          border-bottom: 1px solid #F3F4F6;
          font-size: 11px;
        }

        .info-row:last-child {
          border-bottom: none;
        }

        .info-label {
          font-weight: 600;
          color: #6B7280;
        }

        .info-value {
          color: #111827;
        }

        .status-active {
          color: #22C55E;
          font-weight: 600;
        }

        .status-inactive {
          color: #EF4444;
          font-weight: 600;
        }

        .status-warning {
          color: #F59E0B;
          font-weight: 600;
        }

        .factor-card {
          display: flex;
          gap: 12px;
          padding: 12px;
          background: #F9FAFB;
          border: 1px solid #E5E7EB;
          border-radius: 6px;
          margin-bottom: 8px;
          font-size: 10px;
        }

        .factor-icon {
          width: 20px;
          height: 20px;
          flex-shrink: 0;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 14px;
        }

        .factor-content {
          flex: 1;
        }

        .factor-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 4px;
        }

        .factor-name {
          font-weight: 600;
          color: #111827;
        }

        .factor-points {
          font-weight: 600;
          font-size: 11px;
        }

        .factor-points.positive {
          color: #EF4444;
        }

        .factor-points.negative {
          color: #22C55E;
        }

        .factor-description {
          color: #6B7280;
          line-height: 1.4;
        }

        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #E5E7EB;
          text-align: center;
          font-size: 9px;
          color: #9CA3AF;
        }

        .button-container {
          text-align: center;
          margin: 30px 0;
          padding: 20px;
          background: #F9FAFB;
          border-radius: 8px;
        }

        .print-button {
          background: #005A41;
          color: white;
          padding: 12px 30px;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          margin-right: 10px;
        }

        .print-button:hover {
          background: #004030;
        }

        .close-button {
          background: #E5E7EB;
          color: #111827;
          padding: 12px 30px;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
        }

        .close-button:hover {
          background: #D1D5DB;
        }

        ${includeWatermark ? `
          .watermark-overlay {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 80px;
            font-weight: 900;
            color: rgba(0, 90, 65, 0.08);
            letter-spacing: 8px;
            pointer-events: none;
            z-index: 1000;
            white-space: nowrap;
          }

          .watermark-note {
            background: #FEF3C7;
            border-left: 4px solid #F59E0B;
            padding: 15px;
            margin: 20px 0;
            font-size: 11px;
            color: #92400E;
            line-height: 1.6;
          }

          .watermark-note strong {
            display: block;
            font-size: 12px;
            margin-bottom: 6px;
          }
        ` : ''}
      </style>
    </head>
    <body>
      ${includeWatermark ? `<div class="watermark-overlay">${t.watermark}</div>` : ''}

      <div class="header" style="background: ${brandColor};">
        ${companyLogo ? `<img src="${companyLogo}" alt="Logo" style="max-height: 40px; margin-bottom: 10px;" />` : ''}
        <h1>${t.title}</h1>
        <div class="brand">${brandName}</div>
        <div class="date">${t.generatedAt}: ${currentDate}</div>
      </div>

      ${includeWatermark ? `
        <div class="watermark-note">
          <strong>${t.watermark}</strong>
          ${t.watermarkNote}
        </div>
      ` : ''}

      <div class="company-header">
        <div class="company-name">${company.companyName}</div>
        <div class="company-meta">
          CUI: ${company.cui}${company.registrationNumber ? ` | Nr. Reg. Com: ${company.registrationNumber}` : ''}
        </div>
      </div>

      ${company.riskScore ? `
        <div class="risk-box">
          <div class="risk-label">${t.riskScore}</div>
          <div class="risk-score">
            <div class="risk-value">${company.riskScore.value}</div>
            <div class="risk-level">${company.riskScore.level}</div>
          </div>
        </div>

        ${company.riskScore.explanation ? `
          <div class="risk-explanation">
            ${company.riskScore.explanation}
          </div>
        ` : ''}
      ` : ''}

      <div class="section">
        <div class="section-title">${t.companyInfo}</div>
        <div class="info-row">
          <div class="info-label">${t.address}</div>
          <div class="info-value">${company.address || t.unavailable}</div>
        </div>
        <div class="info-row">
          <div class="info-label">${t.companyStatus}</div>
          <div class="info-value ${company.companyActive ? 'status-active' : 'status-inactive'}">
            ${company.companyActive ? t.active : t.inactive}
          </div>
        </div>
        <div class="info-row">
          <div class="info-label">${t.vatStatus}</div>
          <div class="info-value ${company.vatActive ? 'status-active' : 'status-inactive'}">
            ${company.vatActive ? t.active : t.inactive}
          </div>
        </div>
        ${company.vatSplitRegime !== undefined ? `
          <div class="info-row">
            <div class="info-label">${t.vatSplitRegime}</div>
            <div class="info-value ${company.vatSplitRegime ? 'status-warning' : ''}">${company.vatSplitRegime ? t.yes : t.no}</div>
          </div>
        ` : ''}
        ${company.stateDebts !== undefined ? `
          <div class="info-row">
            <div class="info-label">${t.stateDebts}</div>
            <div class="info-value ${company.stateDebts > 0 ? 'status-inactive' : 'status-active'}">
              ${company.stateDebts > 0 ? `${company.stateDebts.toLocaleString(locale === 'ro' ? 'ro-RO' : 'en-US')} RON` : t.noDebts}
            </div>
          </div>
        ` : ''}
        ${company.activeLawsuits !== undefined ? `
          <div class="info-row">
            <div class="info-label">${t.activeLawsuits}</div>
            <div class="info-value ${company.activeLawsuits > 0 ? 'status-warning' : 'status-active'}">${company.activeLawsuits}</div>
          </div>
        ` : ''}
        ${company.lostCases2y !== undefined ? `
          <div class="info-row">
            <div class="info-label">${t.lostCases2y}</div>
            <div class="info-value ${company.lostCases2y > 0 ? 'status-inactive' : 'status-active'}">${company.lostCases2y}</div>
          </div>
        ` : ''}
        ${company.insolvencyStatus ? `
          <div class="info-row">
            <div class="info-label">${t.insolvencyStatus}</div>
            <div class="info-value ${company.insolvencyStatus === 'none' ? 'status-active' : 'status-inactive'}">
              ${company.insolvencyStatus === 'none' ? t.noProblem : company.insolvencyStatus}
            </div>
          </div>
        ` : ''}
        ${company.bankruptcyFiling !== undefined ? `
          <div class="info-row">
            <div class="info-label">${t.bankruptcyFiling}</div>
            <div class="info-value ${company.bankruptcyFiling ? 'status-inactive' : 'status-active'}">
              ${company.bankruptcyFiling ? t.yes : t.no}
            </div>
          </div>
        ` : ''}
      </div>

      ${company.riskScore?.factors && company.riskScore.factors.length > 0 ? `
        <div class="section page-break">
          <div class="section-title">${t.riskFactors} (${company.riskScore.factors.length})</div>
          ${company.riskScore.factors.map(factor => `
            <div class="factor-card">
              <div class="factor-icon">
                ${factor.impact === 'positive' ? '✓' : factor.impact === 'negative' ? '✗' : '○'}
              </div>
              <div class="factor-content">
                <div class="factor-header">
                  <span class="factor-name">${factor.name}</span>
                  <span class="factor-points ${factor.points > 0 ? 'positive' : 'negative'}">
                    ${factor.points > 0 ? '+' : ''}${factor.points} ${t.points}
                  </span>
                </div>
                <div class="factor-description">${factor.description}</div>
              </div>
            </div>
          `).join('')}
        </div>
      ` : ''}

      <div class="footer">
        <div>${t.footer1}</div>
        <div>${t.footer2}</div>
      </div>

      <div class="button-container no-print">
        <button class="print-button" onclick="window.print()" style="background: ${brandColor};">
          ${t.printButton}
        </button>
        <button class="close-button" onclick="window.close()">
          ${t.closeButton}
        </button>
      </div>

      <script>
        // Auto-focus for better UX
        window.onload = function() {
          // Optional: Auto-print
          // setTimeout(() => window.print(), 500);
        };
      </script>
    </body>
    </html>
  `

  printWindow.document.write(htmlContent)
  printWindow.document.close()
}
